/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1;

//import model.Model;

/**
 *
 * @author arceredillo.adrian
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setTitle("Hiztegia Adrian");
        //JTextAreaHiztegiaIkusi.setEnabled(false);
    }
    
    /**
     * Este método crea el objeto y lo visualiza
     * @return 
     */
    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
                JTextAreaHiztegiaIkusi.setEnabled(false);
                JTextFieldEusUser.setEnabled(false);
                JTextFieldGazUser.setEnabled(false);
            }
        });
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogTerminoaGehitu = new javax.swing.JDialog();
        JLabelUserEus = new javax.swing.JLabel();
        JLabelUserGaz = new javax.swing.JLabel();
        JTextFieldHitzaEus = new javax.swing.JTextField();
        JTextFieldHitzaGaz = new javax.swing.JTextField();
        JButtonUserGehitu = new javax.swing.JButton();
        JButtonItzuli = new javax.swing.JButton();
        JLabelNumId = new javax.swing.JLabel();
        JTextFieldId = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        JLabelTitulo = new javax.swing.JLabel();
        JLabelEuskaraz = new javax.swing.JLabel();
        JLabelGazteleraz = new javax.swing.JLabel();
        JTextFieldEusUser = new javax.swing.JTextField();
        JTextFieldGazUser = new javax.swing.JTextField();
        JButtonTxertatu = new javax.swing.JButton();
        JButtonSalir = new javax.swing.JButton();
        JButtonImprimatu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaHiztegiaIkusi = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        JButtonHitzBakarra = new javax.swing.JButton();

        JDialogTerminoaGehitu.setSize(new java.awt.Dimension(300, 300));

        JLabelUserEus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelUserEus.setText("Euskaraz:");

        JLabelUserGaz.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelUserGaz.setText("Gazteleraz:");

        JButtonUserGehitu.setText("GEHITU");

        JButtonItzuli.setText("ITZULI");

        JLabelNumId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelNumId.setText("Id:");

        javax.swing.GroupLayout JDialogTerminoaGehituLayout = new javax.swing.GroupLayout(JDialogTerminoaGehitu.getContentPane());
        JDialogTerminoaGehitu.getContentPane().setLayout(JDialogTerminoaGehituLayout);
        JDialogTerminoaGehituLayout.setHorizontalGroup(
            JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                        .addComponent(JButtonUserGehitu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonItzuli, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JDialogTerminoaGehituLayout.createSequentialGroup()
                            .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLabelUserGaz)
                                .addComponent(JLabelUserEus)
                                .addComponent(JLabelNumId))
                            .addGap(18, 18, 18)
                            .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTextFieldHitzaGaz, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(JTextFieldHitzaEus)
                                .addComponent(JTextFieldId)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        JDialogTerminoaGehituLayout.setVerticalGroup(
            JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelNumId)
                    .addComponent(JTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldHitzaEus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelUserEus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldHitzaGaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelUserGaz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonItzuli)
                    .addComponent(JButtonUserGehitu))
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        JLabelTitulo.setText("HIZTEGIA");

        JLabelEuskaraz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelEuskaraz.setText("Euskaraz:");

        JLabelGazteleraz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelGazteleraz.setText("Gazteleraz:");

        JButtonTxertatu.setText("TERMINOA GEHITU");
        JButtonTxertatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonTxertatuActionPerformed(evt);
            }
        });

        JButtonSalir.setText("IRTEN");

        JButtonImprimatu.setText("HIZTEGIA IMPRIMATU");

        JTextAreaHiztegiaIkusi.setColumns(20);
        JTextAreaHiztegiaIkusi.setRows(5);
        jScrollPane1.setViewportView(JTextAreaHiztegiaIkusi);

        JButtonHitzBakarra.setText("Hitz hau bakarrik");
        JButtonHitzBakarra.setActionCommand("Hitz hau bakarrik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelEuskaraz)
                                .addGap(28, 28, 28)
                                .addComponent(JTextFieldEusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JLabelGazteleraz)
                                .addGap(18, 18, 18)
                                .addComponent(JTextFieldGazUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JButtonTxertatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonImprimatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonHitzBakarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(JLabelTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelEuskaraz)
                            .addComponent(JTextFieldEusUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextFieldGazUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelGazteleraz))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(JButtonHitzBakarra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonTxertatu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonImprimatu))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JButtonSalir)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonTxertatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonTxertatuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JButtonTxertatuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JButtonHitzBakarra;
    public static javax.swing.JButton JButtonImprimatu;
    public static javax.swing.JButton JButtonItzuli;
    static javax.swing.JButton JButtonSalir;
    static javax.swing.JButton JButtonTxertatu;
    public static javax.swing.JButton JButtonUserGehitu;
    public static javax.swing.JDialog JDialogTerminoaGehitu;
    private javax.swing.JLabel JLabelEuskaraz;
    public static javax.swing.JLabel JLabelGazteleraz;
    public static javax.swing.JLabel JLabelNumId;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JLabel JLabelUserEus;
    public static javax.swing.JLabel JLabelUserGaz;
    public static javax.swing.JTextArea JTextAreaHiztegiaIkusi;
    public static javax.swing.JTextField JTextFieldEusUser;
    public static javax.swing.JTextField JTextFieldGazUser;
    public static javax.swing.JTextField JTextFieldHitzaEus;
    public static javax.swing.JTextField JTextFieldHitzaGaz;
    public static javax.swing.JTextField JTextFieldId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    
}
