/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bocetosGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author AdriAlex
 */
public class BocetoGUI_TextReport extends javax.swing.JFrame {

    /**
     * Creates new form BocetoGUI_TextReport
     */
    public BocetoGUI_TextReport() {
        initComponents();
        this.setTitle("Text Reports");
        this.setResizable(false);
        JComboBoxTxostenak.addItem("...");
        JComboBoxTxostenak.addItem("Today's occupation");
        JComboBoxTxostenak.addItem("Specific customer's purchases");
        JComboBoxTxostenak.addItem("Total earned with purchases");
        JComboBoxTxostenak.addItem("Underage customers");
        JComboBoxTxostenak.addItem("View all reserbations");
        
        
        JSpinnerCustomerId.setValue(0);
        JSpinnerCustomerId.setEnabled(false);
        JTextAreaTxostenak.setAutoscrolls(true);
        JTextAreaTxostenak.setEditable(false);
        
        JTextFieldTodaysDate.setText("dd/mm/yyyy");
        JTextFieldTodaysDate.setEditable(false);
        JTextFieldTodaysDate.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelTitulo = new javax.swing.JLabel();
        JLabelIntro = new javax.swing.JLabel();
        JComboBoxTxostenak = new javax.swing.JComboBox<>();
        JButtonPrintTxosten = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTextAreaTxostenak = new javax.swing.JTextArea();
        JButtonReturnStart = new javax.swing.JButton();
        JLabelSpecifyId = new javax.swing.JLabel();
        JSpinnerCustomerId = new javax.swing.JSpinner();
        JLabelSpecifyDate = new javax.swing.JLabel();
        JTextFieldTodaysDate = new javax.swing.JTextField();
        JButtonSaveInFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTitulo.setText("Garage HALAB");

        JLabelIntro.setText("Welcome to Garage HALAB's official GUI.");

        JComboBoxTxostenak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxTxostenakActionPerformed(evt);
            }
        });

        JButtonPrintTxosten.setText("View");
        JButtonPrintTxosten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonPrintTxostenActionPerformed(evt);
            }
        });

        JTextAreaTxostenak.setColumns(20);
        JTextAreaTxostenak.setLineWrap(true);
        JTextAreaTxostenak.setRows(5);
        jScrollPane3.setViewportView(JTextAreaTxostenak);

        JButtonReturnStart.setText("Go back");

        JLabelSpecifyId.setText("Specify ID:");

        JLabelSpecifyDate.setText("Enter date:");

        JButtonSaveInFile.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLabelIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JComboBoxTxostenak, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JButtonPrintTxosten, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(JButtonReturnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JLabelSpecifyId, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(JSpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(JLabelSpecifyDate)
                            .addComponent(JTextFieldTodaysDate)
                            .addComponent(JButtonSaveInFile, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelIntro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboBoxTxostenak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonPrintTxosten)
                    .addComponent(JButtonReturnStart))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelSpecifyId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JSpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLabelSpecifyDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextFieldTodaysDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonSaveInFile, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxTxostenakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxTxostenakActionPerformed
        // TODO add your handling code here:
        JTextAreaTxostenak.setText("Waiting for a report request...");
        
        if (JComboBoxTxostenak.getSelectedIndex() == 0) {
            System.out.println("Actual report: No report selected. Please, choose one and press the 'View' button. \n");
            
        } else if (JComboBoxTxostenak.getSelectedIndex() == 1) {
            
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString());
            System.out.println("\t-> Introduce una fecha para ver las reservas existentes. \n");
            JTextFieldTodaysDate.setEditable(true);
            JTextFieldTodaysDate.setEnabled(true);
            JSpinnerCustomerId.setEnabled(false);
            JTextFieldTodaysDate.setText("");
            
        } else if (JComboBoxTxostenak.getSelectedIndex() == 2) {
            JSpinnerCustomerId.setEnabled(true);
            JTextFieldTodaysDate.setEnabled(false);
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString());
            System.out.println("\t-> A continuación, podrás ver las compras que ha realizado un cliente determinado. Para ello, ingresa el id de dicho cliente. \n");
            
        } else {
            System.out.println("Choose any option from the combo box and press 'View'. \n");
            JTextFieldTodaysDate.setEditable(false);
            JTextFieldTodaysDate.setEnabled(false);
            JSpinnerCustomerId.setEnabled(false);
        } 
        
    }//GEN-LAST:event_JComboBoxTxostenakActionPerformed

    private void JButtonPrintTxostenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonPrintTxostenActionPerformed
        // TODO add your handling code here:
        
        if (JComboBoxTxostenak.getSelectedIndex() == 0) {
            JTextAreaTxostenak.setText("Waiting for a report request...");
            System.out.println("No request selected...\n");
            
        } else if (JComboBoxTxostenak.getSelectedIndex() == 1) {
            if (JTextFieldTodaysDate.getText().equals("..") || JTextFieldTodaysDate.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"The entered date value is not valid! Try again. ", "Error",JOptionPane.WARNING_MESSAGE);
            } else {
                JTextAreaTxostenak.setText("Searching desired date's occupation... " + "(" + JTextFieldTodaysDate.getText() + ")");
            }        
            
        } else if (JComboBoxTxostenak.getSelectedIndex() == 2) {
            
            if (JSpinnerCustomerId.getValue().toString().equals("0")) {
                JOptionPane.showMessageDialog(null,"Debes introducir la ID de un cliente para continuar! ", "Error",JOptionPane.WARNING_MESSAGE);
                System.out.println("Debes meter un ID de un cliente! ");
            }
            
            //JSpinnerCustomerId.setEnabled(true);
            JTextAreaTxostenak.setText(JSpinnerCustomerId.getValue().toString());
            
        } 
    }//GEN-LAST:event_JButtonPrintTxostenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_TextReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_TextReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_TextReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_TextReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BocetoGUI_TextReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JButtonPrintTxosten;
    public static javax.swing.JButton JButtonReturnStart;
    public static javax.swing.JButton JButtonSaveInFile;
    public static javax.swing.JComboBox<String> JComboBoxTxostenak;
    public static javax.swing.JLabel JLabelIntro;
    public static javax.swing.JLabel JLabelSpecifyDate;
    public static javax.swing.JLabel JLabelSpecifyId;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JSpinner JSpinnerCustomerId;
    public static javax.swing.JTextArea JTextAreaTxostenak;
    public static javax.swing.JTextField JTextFieldTodaysDate;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
