package bocetosGUI;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arceredillo.adrian
 */
public class BocetoGUI_login extends javax.swing.JFrame {

    /**
     * Creates new form BocetoGUI
     */
    public BocetoGUI_login() {
        initComponents();
        this.setTitle("Garage HALAB");
        this.setResizable(false);
        JComboBoxAdminUsers.addItem("...");
        JComboBoxAdminUsers.addItem("admin1");
        JComboBoxAdminUsers.addItem("admin2");
        
        JTextFieldAdminPassword.setEditable(false);
        JTextFieldAdminPassword.setEnabled(false);
        
        JButtonValidateAdmin.setEnabled(false);
        
    }
    
    public void paint(Graphics draw) {
        //esto solamente lo utilizaré para darle un nuevo color de fondo al jframe
        //getContentPane().setBackground(new Color(70, 80, 70));
        //getContentPane().setBackground(new Color(153, 153, 255));
        getContentPane().setBackground(new Color(60, 63, 65));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelTitulo = new javax.swing.JLabel();
        JComboBoxAdminUsers = new javax.swing.JComboBox<>();
        JLabelIntro2 = new javax.swing.JLabel();
        JLabelMensaje = new javax.swing.JLabel();
        JTextFieldAdminPassword = new javax.swing.JTextField();
        JCheckBoxPrueba = new javax.swing.JCheckBox();
        JButtonValidateAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setForeground(java.awt.Color.pink);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        JLabelTitulo.setText("Garage HALAB");

        JComboBoxAdminUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxAdminUsersActionPerformed(evt);
            }
        });

        JLabelIntro2.setForeground(new java.awt.Color(153, 153, 153));
        JLabelIntro2.setText("Are you qualified for this? Private content. Only for staff.");

        JLabelMensaje.setForeground(new java.awt.Color(153, 153, 153));
        JLabelMensaje.setText("Enter admin's password to continue");

        JTextFieldAdminPassword.setText("enter password");

        JCheckBoxPrueba.setText("Accept the terms of Halab Garage's company. Read it.");
        JCheckBoxPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckBoxPruebaActionPerformed(evt);
            }
        });

        JButtonValidateAdmin.setText("Confirm!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(JLabelMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(JButtonValidateAdmin)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelIntro2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(JLabelTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JTextFieldAdminPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JComboBoxAdminUsers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(JCheckBoxPrueba))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JLabelTitulo)
                .addGap(12, 12, 12)
                .addComponent(JLabelMensaje)
                .addGap(18, 18, 18)
                .addComponent(JComboBoxAdminUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTextFieldAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelIntro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(JButtonValidateAdmin)
                .addGap(18, 18, 18)
                .addComponent(JCheckBoxPrueba)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxAdminUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxAdminUsersActionPerformed
        // TODO add your handling code here:
        
        String passAdmin1 = "unoAdmin";
        String passAdmin2 = "dosAdmin";
        
        if (JComboBoxAdminUsers.getSelectedIndex() == 0) {
            System.out.println("No admin user selected yet. \n");
            JTextFieldAdminPassword.setText("enter password");
            
            JTextFieldAdminPassword.setEditable(false); JTextFieldAdminPassword.setEnabled(false); 
            
            
        } else if (JComboBoxAdminUsers.getSelectedIndex() == 1) {
            System.out.println("Enter the password for " + JComboBoxAdminUsers.getSelectedItem());
            JTextFieldAdminPassword.setText("");
            
            JTextFieldAdminPassword.setEditable(true);  JTextFieldAdminPassword.setEnabled(true);
            
        } else if (JComboBoxAdminUsers.getSelectedIndex() == 2) {
            System.out.println("Enter the password for " + JComboBoxAdminUsers.getSelectedItem());
            JTextFieldAdminPassword.setText("");
            
            JTextFieldAdminPassword.setEditable(true);  JTextFieldAdminPassword.setEnabled(true);
            
        }

    }//GEN-LAST:event_JComboBoxAdminUsersActionPerformed

    private void JCheckBoxPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckBoxPruebaActionPerformed
        // TODO add your handling code here:s
        
        if (JComboBoxAdminUsers.getSelectedIndex() == 1 && (!JTextFieldAdminPassword.getText().equals(""))) {
            if (JCheckBoxPrueba.isSelected()) {
                JButtonValidateAdmin.setEnabled(true);
            } else {
                JButtonValidateAdmin.setEnabled(false);
            }
        } else if (JComboBoxAdminUsers.getSelectedIndex() == 2 && (!JTextFieldAdminPassword.getText().equals(""))) {
            if (JCheckBoxPrueba.isSelected()) {
                JButtonValidateAdmin.setEnabled(true);
            } else {
                JButtonValidateAdmin.setEnabled(false);
            }
        } else {
            JButtonValidateAdmin.setEnabled(false);
        }
        
        /*
        if (JCheckBoxPrueba.isSelected()) {
                JButtonValidateAdmin.setEnabled(true);
            } else {
                JButtonValidateAdmin.setEnabled(false);
            }
        */
    }//GEN-LAST:event_JCheckBoxPruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BocetoGUI_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BocetoGUI_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JButtonValidateAdmin;
    public static javax.swing.JCheckBox JCheckBoxPrueba;
    public static javax.swing.JComboBox<String> JComboBoxAdminUsers;
    public static javax.swing.JLabel JLabelIntro2;
    public static javax.swing.JLabel JLabelMensaje;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JTextField JTextFieldAdminPassword;
    // End of variables declaration//GEN-END:variables
}

