/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3;

//import model.Model;

import pkg2.*;
import java.awt.Color;
import java.awt.Graphics;


/**
 *
 * @author arceredillo.adrian
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setTitle("Hiztegia Adrian");
//        JTextAreaHiztegiaIkusi.setEnabled(false);
        JTextFieldMail.setEnabled(false);
        
    }
    
    public void paint(Graphics draw) {
        //esto solamente lo utilizaré para darle un nuevo color de fondo al jframe
        getContentPane().setBackground(new Color(70, 80, 70));
    }
    
    /**
     * Este método crea el objeto y lo visualiza
     * @return 
     */
    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
                JTextAreaHiztegiaIkusi.setEnabled(false);
            }
        });
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogTerminoaGehitu = new javax.swing.JDialog();
        JLabelApellido = new javax.swing.JLabel();
        JLabelEdad = new javax.swing.JLabel();
        JTextFieldApellido = new javax.swing.JTextField();
        JTextFieldEdad = new javax.swing.JTextField();
        JButtonUserGehitu = new javax.swing.JButton();
        JButtonItzuli = new javax.swing.JButton();
        JLabelNombre = new javax.swing.JLabel();
        JTextFieldNombre = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        JLabelTelefono = new javax.swing.JLabel();
        JTextFieldTelefono = new javax.swing.JTextField();
        JLabelMail = new javax.swing.JLabel();
        JTextFieldMail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        JDialog2Table = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableRegistros = new javax.swing.JTable();
        JLabelTitulo = new javax.swing.JLabel();
        JLabelApellidoTitulo = new javax.swing.JLabel();
        JLabelTituloEdad = new javax.swing.JLabel();
        JTextFieldApellidoUser = new javax.swing.JTextField();
        JTextFieldEdadUser = new javax.swing.JTextField();
        JButtonTxertatu = new javax.swing.JButton();
        JButtonSalir = new javax.swing.JButton();
        JButtonImprimatu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaHiztegiaIkusi = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        JButtonTraducir = new javax.swing.JButton();
        JButtonRegistrosTable = new javax.swing.JButton();
        JButtonVerClientes = new javax.swing.JButton();

        JDialogTerminoaGehitu.setSize(new java.awt.Dimension(300, 300));

        JLabelApellido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelApellido.setText("Surname:");

        JLabelEdad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelEdad.setText("Age:");

        JButtonUserGehitu.setText("ADD");
        JButtonUserGehitu.setActionCommand("GEHITU CLIENT");

        JButtonItzuli.setText("ATZERA");

        JLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelNombre.setText("Name:");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTitulo.setText("Enter the new Customer's info:");

        JLabelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelTelefono.setText("Phone Number:");

        JLabelMail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelMail.setText("Mail:");

        javax.swing.GroupLayout JDialogTerminoaGehituLayout = new javax.swing.GroupLayout(JDialogTerminoaGehitu.getContentPane());
        JDialogTerminoaGehitu.getContentPane().setLayout(JDialogTerminoaGehituLayout);
        JDialogTerminoaGehituLayout.setHorizontalGroup(
            JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                                .addComponent(JButtonUserGehitu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButtonItzuli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                                        .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLabelEdad)
                                            .addComponent(JLabelApellido)
                                            .addComponent(JLabelNombre)
                                            .addComponent(JLabelMail))
                                        .addGap(61, 61, 61)
                                        .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTextFieldApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(JTextFieldNombre)
                                            .addComponent(JTextFieldMail)
                                            .addComponent(JTextFieldEdad)))
                                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                                        .addComponent(JLabelTelefono)
                                        .addGap(18, 18, 18)
                                        .addComponent(JTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JDialogTerminoaGehituLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
        );
        JDialogTerminoaGehituLayout.setVerticalGroup(
            JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelNombre)
                    .addComponent(JTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelApellido)
                    .addComponent(JTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelEdad)
                    .addComponent(JTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelMail)
                    .addComponent(JTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelTelefono)
                    .addComponent(JTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonUserGehitu)
                    .addComponent(JButtonItzuli))
                .addGap(29, 29, 29))
        );

        JDialog2Table.setSize(new java.awt.Dimension(300, 300));

        JTableRegistros.setModel(new TerminoenTableModela(Model.registrosArrayList()));
        jScrollPane2.setViewportView(JTableRegistros);

        javax.swing.GroupLayout JDialog2TableLayout = new javax.swing.GroupLayout(JDialog2Table.getContentPane());
        JDialog2Table.getContentPane().setLayout(JDialog2TableLayout);
        JDialog2TableLayout.setHorizontalGroup(
            JDialog2TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog2TableLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        JDialog2TableLayout.setVerticalGroup(
            JDialog2TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog2TableLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(153, 255, 153));
        JLabelTitulo.setText("VER CLIENTES");

        JLabelApellidoTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelApellidoTitulo.setForeground(new java.awt.Color(153, 255, 153));
        JLabelApellidoTitulo.setText("Apellido:");

        JLabelTituloEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelTituloEdad.setForeground(new java.awt.Color(153, 255, 153));
        JLabelTituloEdad.setText("Edad:");

        JButtonTxertatu.setText("New Client");

        JButtonSalir.setText("IRTEN");

        JButtonImprimatu.setText("HIZTEGIA IMPRIMATU");

        JTextAreaHiztegiaIkusi.setColumns(20);
        JTextAreaHiztegiaIkusi.setRows(5);
        jScrollPane1.setViewportView(JTextAreaHiztegiaIkusi);

        jSeparator1.setForeground(new java.awt.Color(153, 255, 153));

        JButtonTraducir.setText("ITZULI");

        JButtonRegistrosTable.setText("HIZTEGIA JTABLEAN");

        JButtonVerClientes.setText("CLIENTES");
        JButtonVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVerClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelTituloEdad)
                                .addGap(18, 18, 18)
                                .addComponent(JTextFieldEdadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelApellidoTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTextFieldApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(JButtonTraducir)
                        .addGap(43, 43, 43)
                        .addComponent(JButtonVerClientes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JLabelTitulo)
                                .addGap(407, 407, 407))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JButtonTxertatu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JButtonImprimatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButtonRegistrosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(JLabelTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelApellidoTitulo)
                            .addComponent(JTextFieldApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelTituloEdad)
                            .addComponent(JTextFieldEdadUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JButtonTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JButtonVerClientes)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonTxertatu)
                    .addComponent(JButtonImprimatu)
                    .addComponent(JButtonRegistrosTable))
                .addGap(18, 18, 18)
                .addComponent(JButtonSalir)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVerClientesActionPerformed
        // TODO add your handling code here:
        System.out.println("a");
    }//GEN-LAST:event_JButtonVerClientesActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton JButtonImprimatu;
    public static javax.swing.JButton JButtonItzuli;
    public static javax.swing.JButton JButtonRegistrosTable;
    public static javax.swing.JButton JButtonSalir;
    public static javax.swing.JButton JButtonTraducir;
    public static javax.swing.JButton JButtonTxertatu;
    public static javax.swing.JButton JButtonUserGehitu;
    public static javax.swing.JButton JButtonVerClientes;
    public static javax.swing.JDialog JDialog2Table;
    public static javax.swing.JDialog JDialogTerminoaGehitu;
    public static javax.swing.JLabel JLabelApellido;
    public static javax.swing.JLabel JLabelApellidoTitulo;
    public static javax.swing.JLabel JLabelEdad;
    public static javax.swing.JLabel JLabelMail;
    public static javax.swing.JLabel JLabelNombre;
    public static javax.swing.JLabel JLabelTelefono;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JLabel JLabelTituloEdad;
    public static javax.swing.JTable JTableRegistros;
    public static javax.swing.JTextArea JTextAreaHiztegiaIkusi;
    public static javax.swing.JTextField JTextFieldApellido;
    public static javax.swing.JTextField JTextFieldApellidoUser;
    public static javax.swing.JTextField JTextFieldEdad;
    public static javax.swing.JTextField JTextFieldEdadUser;
    public static javax.swing.JTextField JTextFieldMail;
    public static javax.swing.JTextField JTextFieldNombre;
    public static javax.swing.JTextField JTextFieldTelefono;
    public static javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
