/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1;

//import model.Model;

/**
 *
 * @author arceredillo.adrian
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setTitle("Hiztegia Adrian");
//        JTextAreaHiztegiaIkusi.setEnabled(false);
        JTextFieldId.setEnabled(false);
    }
    
    /**
     * Este método crea el objeto y lo visualiza
     * @return 
     */
    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
                JTextAreaHiztegiaIkusi.setEnabled(false);
            }
        });
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogTerminoaGehitu = new javax.swing.JDialog();
        JLabelUserEus = new javax.swing.JLabel();
        JLabelUserGaz = new javax.swing.JLabel();
        JTextFieldHitzaEus = new javax.swing.JTextField();
        JTextFieldHitzaGaz = new javax.swing.JTextField();
        JButtonUserGehitu = new javax.swing.JButton();
        JButtonItzuli = new javax.swing.JButton();
        JLabelId = new javax.swing.JLabel();
        JTextFieldId = new javax.swing.JTextField();
        JDialog2Table = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableRegistros = new javax.swing.JTable();
        JLabelTitulo = new javax.swing.JLabel();
        JLabelEuskaraz = new javax.swing.JLabel();
        JLabelGazteleraz = new javax.swing.JLabel();
        JTextFieldEusUser = new javax.swing.JTextField();
        JTextFieldGazUser = new javax.swing.JTextField();
        JButtonTxertatu = new javax.swing.JButton();
        JButtonSalir = new javax.swing.JButton();
        JButtonImprimatu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaHiztegiaIkusi = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        JButtonTraducir = new javax.swing.JButton();
        JButtonRegistrosTable = new javax.swing.JButton();

        JDialogTerminoaGehitu.setSize(new java.awt.Dimension(300, 300));

        JLabelUserEus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelUserEus.setText("Euskaraz:");

        JLabelUserGaz.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelUserGaz.setText("Gazteleraz:");

        JButtonUserGehitu.setText("GEHITU");

        JButtonItzuli.setText("ATZERA");

        JLabelId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLabelId.setText("Id:");

        javax.swing.GroupLayout JDialogTerminoaGehituLayout = new javax.swing.GroupLayout(JDialogTerminoaGehitu.getContentPane());
        JDialogTerminoaGehitu.getContentPane().setLayout(JDialogTerminoaGehituLayout);
        JDialogTerminoaGehituLayout.setHorizontalGroup(
            JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                        .addComponent(JButtonUserGehitu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonItzuli, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                        .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelUserGaz)
                            .addComponent(JLabelUserEus)
                            .addComponent(JLabelId))
                        .addGap(18, 18, 18)
                        .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextFieldHitzaEus)
                            .addComponent(JTextFieldHitzaGaz, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(JTextFieldId))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        JDialogTerminoaGehituLayout.setVerticalGroup(
            JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTerminoaGehituLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelUserEus)
                    .addComponent(JTextFieldHitzaEus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelUserGaz)
                    .addComponent(JTextFieldHitzaGaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(JDialogTerminoaGehituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonUserGehitu)
                    .addComponent(JButtonItzuli))
                .addGap(29, 29, 29))
        );

        JDialog2Table.setSize(new java.awt.Dimension(300, 300));

        JTableRegistros.setModel(new TerminoenTableModela(Model.registrosArrayList()));
        jScrollPane2.setViewportView(JTableRegistros);

        javax.swing.GroupLayout JDialog2TableLayout = new javax.swing.GroupLayout(JDialog2Table.getContentPane());
        JDialog2Table.getContentPane().setLayout(JDialog2TableLayout);
        JDialog2TableLayout.setHorizontalGroup(
            JDialog2TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog2TableLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        JDialog2TableLayout.setVerticalGroup(
            JDialog2TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog2TableLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        JLabelTitulo.setText("HIZTEGIA");

        JLabelEuskaraz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelEuskaraz.setText("Euskaraz:");

        JLabelGazteleraz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelGazteleraz.setText("Gazteleraz:");

        JButtonTxertatu.setText("TERMINOA GEHITU");

        JButtonSalir.setText("IRTEN");

        JButtonImprimatu.setText("HIZTEGIA IMPRIMATU");

        JTextAreaHiztegiaIkusi.setColumns(20);
        JTextAreaHiztegiaIkusi.setRows(5);
        jScrollPane1.setViewportView(JTextAreaHiztegiaIkusi);

        JButtonTraducir.setText("ITZULI");

        JButtonRegistrosTable.setText("HIZTEGIA JTABLEAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelEuskaraz)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelGazteleraz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTextFieldEusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextFieldGazUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(JButtonTraducir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JLabelTitulo)
                                .addGap(407, 407, 407))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JButtonTxertatu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JButtonImprimatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButtonRegistrosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(JLabelTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelEuskaraz)
                            .addComponent(JTextFieldEusUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelGazteleraz)
                            .addComponent(JTextFieldGazUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JButtonTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonTxertatu)
                    .addComponent(JButtonImprimatu)
                    .addComponent(JButtonRegistrosTable))
                .addGap(18, 18, 18)
                .addComponent(JButtonSalir)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton JButtonImprimatu;
    public static javax.swing.JButton JButtonItzuli;
    public static javax.swing.JButton JButtonRegistrosTable;
    public static javax.swing.JButton JButtonSalir;
    public static javax.swing.JButton JButtonTraducir;
    public static javax.swing.JButton JButtonTxertatu;
    public static javax.swing.JButton JButtonUserGehitu;
    public static javax.swing.JDialog JDialog2Table;
    public static javax.swing.JDialog JDialogTerminoaGehitu;
    private javax.swing.JLabel JLabelEuskaraz;
    public static javax.swing.JLabel JLabelGazteleraz;
    public static javax.swing.JLabel JLabelId;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JLabel JLabelUserEus;
    public static javax.swing.JLabel JLabelUserGaz;
    public static javax.swing.JTable JTableRegistros;
    public static javax.swing.JTextArea JTextAreaHiztegiaIkusi;
    public static javax.swing.JTextField JTextFieldEusUser;
    public static javax.swing.JTextField JTextFieldGazUser;
    public static javax.swing.JTextField JTextFieldHitzaEus;
    public static javax.swing.JTextField JTextFieldHitzaGaz;
    public static javax.swing.JTextField JTextFieldId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
